### ISSUE TITLE
新版本插件自启动失效

### ISSUE THREAD

**Issue by K1ng97** [gobysec/GobyExtension#14]
![image](https://user-images.githubusercontent.com/59076418/113502123-c768dc00-955c-11eb-9c7f-8e3f875e5a39.png)

新版自启动接口貌似失效

**Comment by gobysec** [comment]
initEvent 是安装插件后初始化执行的事件,不是每次Goby启动都会执行

**Comment by wangcl666** [comment]
表哥在开发什么插件?
