### ISSUE TITLE
关于插件问题

### ISSUE THREAD

**Issue by sun-kids** [gobysec/GobyExtension#16]
插件无法识别，并且异常的卡，访问插件市场也很慢
![image](https://user-images.githubusercontent.com/74457236/116089067-0f4ecf00-a6d5-11eb-9652-eec0c6e0dbcd.png)
![image](https://user-images.githubusercontent.com/74457236/116089109-17a70a00-a6d5-11eb-9c29-ab556bc11d72.png)

**Comment by gobysec** [comment]
收到，请问是哪个版本。

**Comment by gobysec** [comment]
收到，插件目录是否存在其它无关文件夹? 可以看一下是否有的插件内部文件无数据?
