### ISSUE TITLE
无法登录和使用插件

### ISSUE THREAD

**Issue by 132admin** [gobysec/GobyExtension#17]
![image](https://user-images.githubusercontent.com/77607983/118061377-6e942b00-b3c7-11eb-8d34-d194ae8db9fe.png)
![image](https://user-images.githubusercontent.com/77607983/118061721-11e54000-b3c8-11eb-9145-778a14b64ff6.png)

**Comment by gobysec** [comment]
网络问题 Goby 在外网

132admin ***@***.***> 于2021年5月13日周四 上午8:47写道：

**Comment by 132admin** [comment]
可以扫描，也是外网

**Comment by 132admin** [comment]
可以扫描，也是外网

**Comment by gobysec** [comment]
可以先试下访问官网。可以添加微信：gobyteam

132admin ***@***.***> 于2021年5月13日周四 上午9:55写道：
