### ISSUE TITLE
ExportCsv插件导出内容较大时出现bug

### ISSUE THREAD

**Issue by kesonn** [gobysec/GobyExtension#21]
![image](https://user-images.githubusercontent.com/36539433/119378301-b59bed80-bcf0-11eb-87f4-eb0d635c7895.png)
ExportCsv插件导出的内容较大时出现bug，直接显示“导出成功”，实际上没有弹出来文件保存位置的窗口，下载文件失败～～

**Comment by kesonn** [comment]
发现是mac下导出有问题，win下导出成功。

**Comment by gobysec** [comment]
收到反馈，我们会尽快优化。
方便提供win下文件下载后有多大吗?

**Comment by kesonn** [comment]
897kb，一共26898行

**Comment by gobysec** [comment]
方便联系gobybot吗?

**Comment by gobysec** [comment]
已定位到问题，会尽快修复,感谢反馈！
