### ISSUE TITLE
dirsearch插件

### ISSUE THREAD

**Issue by Baikeryoyo** [gobysec/GobyExtension#22]
Usage: dirsearch.py [-u|--url] target [-e|--extensions] extensions [options]

dirsearch.py: error: no such option: --format
报上面错误
配置如下
goby和dirsearch不在同一个目录
dirsearch版本为最新版本0.4.1
![image](https://user-images.githubusercontent.com/57838797/120262001-a823cc00-c2cb-11eb-8c17-29bd313811fa.png)

**Comment by gobysec** [comment]
收到反馈,会跟作者进行确认

**Comment by Baikeryoyo** [comment]
> 收到反馈，会跟作者进行确认
更新信息，目录中不能存在文件夹有空格的情况，且dirsearch要在插件的目录下才可以

**Comment by gobysec** [comment]
-w 参数需要是字典的绝对路径
