### ISSUE TITLE
漏洞页面没有msf按钮

### ISSUE THREAD

**Issue by Sunglassescat** [gobysec/GobyExtension#23]

**Comment by gobysec** [comment]
![image](https://user-images.githubusercontent.com/50955360/122325883-f4bf0680-cf5d-11eb-8a1d-e51b8f738eeb.png)

确定一下是这个漏洞吗?

**Comment by connected201** [comment]
yes, i confirm, on vulnerability page msf button don't appear!  
 

![](https://user-images.githubusercontent.com/20506433/154343037-0fa631b7-410d-4f9f-bcf9-9da9daedac3f.png)

![](https://user-images.githubusercontent.com/20506433/154342671-262a6e83-38f0-4e14-8407-7e2341e70af1.png)

![](https://user-images.githubusercontent.com/20506433/154342262-3c2836d2-d715-408b-9c3a-56e818da0d91.png)
