### ISSUE TITLE
springboot_scan插件可导致xss漏洞

### ISSUE THREAD

**Issue by Linklelo** [gobysec/GobyExtension#36]
![image](https://user-images.githubusercontent.com/25213195/142584110-4ebdca39-6c6d-43df-85eb-d7eeb7db3656.png)

![image](https://user-images.githubusercontent.com/25213195/142584077-6d8bcf88-cd41-4805-bc03-f0ba544498b4.png)

**Comment by Conan924** [comment]
谢谢师傅，已更新
