### ISSUE TITLE
希望goby的xray插件一个扫描任务单独生成一个报告，往后翻报告找漏洞 稍微有点迷

### ISSUE THREAD

**Issue by hanchen666** [gobysec/GobyExtension#6]
11111，作者翻我翻我

**Comment by gobysec** [comment]
> 11111，作者翻我翻我

作者回复：请更新最新版插件，报告在前面

**Comment by hanchen666** [comment]
感谢作者------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Goby&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月22日(星期二) 下午5:21
收件人:&nbsp;&quot;gobysec/GobyExtension&quot;<GobyExtension@noreply.github.com&gt;;
抄送:&nbsp;&quot;hanchen666&quot;<2535346559@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gobysec/GobyExtension] 希望goby的xray插件一个扫描任务单独生成一个报告，往后翻报告找漏洞 稍微有点迷 (#6)
