### ISSUE TITLE
插件上传失败

### ISSUE THREAD

**Issue by Alazyworm233** [gobysec/GobyExtension#62]
写了个小插件，但是非常难受，上传老是出现README file does not exist，明明就在包里面啊。

**Comment by 0xn0ne** [comment]
怎么解决的。。我也碰到了

**Comment by 0xn0ne** [comment]
![image](https://user-images.githubusercontent.com/16507416/195163602-53f0c6ca-2f09-4044-b396-eeff4ea586a9.png)
